name: React Tests

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    name: Run React Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18] # Test with multiple Node.js versions

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm # Cache directory for npm; use `~/.yarn` for Yarn
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-

      - name: Install dependencies
        run: npm ci # Use npm ci for a clean, fast install with lockfile

      - name: Run tests
        run: npm test
